<a href="https://colab.research.google.com/github/AadeshVarude/AadeshVarude/blob/main/DL_ASS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import copy


In [2]:
def problem_1a (A, B):
  return A + B
def problem_1b (A, B, C):
  return np.dot(A,B)-C
def problem_1c (A, B, C):
  return np.dot(A,B)+np.transpose(C)
def problem_1d (x, y):
  return np.dot(np.transpose(x),y)
def problem_1e (A, x):
  return np.linalg.solve(A,x)
def problem_1f (A, i):
  return np.sum(A[i,::2])
def problem_1g (A, c, d):
  return np.mean(A[np.nonzero((A<=d) & (A>=c))])
def problem_1h (A, k):
  w,v=np.linalg.eig(B)
  w=np.abs(w)
  ind=np.argsort(-w)
  return v[:,ind[:k]]
def problem_1i (x, k, m, s):
  z=np.ones([len(x)])
  mean=x+np.dot(m,z)
  covar=s*np.identity(len(x))
  return np.random.multivariate_normal(mean,covar,k).transpose()
def problem_1j (A):
  ind=np.random.permutation(len(A[0]))
  return A[:,ind]
def problem_1k (x):
  mean=np.mean(x)
  std=np.std(x)
  return (x-mean)/std
def problem_1l (x, k):
  return np.repeat(np.atleast_2d(x),k,axis=-1)
def problem_1m (X, Y):
  k,n=X.shape
  k,m=Y.shape
  x=np.repeat(np.atleast_3d(X),m,axis=-1)
  y=np.repeat(np.atleast_3d(Y),n,axis=-1)
  y=np.swapaxes(y, 1, 2)
  D=np.sqrt(np.sum(np.square(x-y), axis=0))
  return D
def problem_1n (matrices):
  nums_mul=0
  for i in range(len(matrices)-1):
    nums_mul+=matrices[i].shape[0]*matrices[i].shape[1]*matrices[i+1].shape[1]
  return nums_mul

In [7]:
A1 = np.array([[1,2,3],[4,5,6]])
A2 = np.array([[7,8],[9,10],[11,12]])
A3 = np.array([[13,14],[15,16]])
problem_1n ([A1,A2])

12

In [ ]:
A=np.arange(9).reshape((1,9))
B=np.arange(9).reshape((3, 3))
C=np.arange(12).reshape((3, 4))
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
from functools import reduce
import operator
matrices=[B,C]
dim=[]
for i in matrices:
  dim.append(i.shape[1])
print(dim)
dims = [A.shape[1] for A in matrices]
result = reduce(operator.mul, dims)
result

[3, 4]


12

In [ ]:
x=np.arange(9).reshape((9,1))
x
b=np.repeat(np.atleast_3d(B),4,axis=-1)
# b=np.swapaxes(b, , 2)
print(b)
c=np.repeat(np.atleast_3d(C),3,axis=-1)
c=np.swapaxes(c, 1, 2)
print(c)
np.sum(np.square(b-c),axis=0)

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[3 3 3 3]
  [4 4 4 4]
  [5 5 5 5]]

 [[6 6 6 6]
  [7 7 7 7]
  [8 8 8 8]]]
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]]]


array([[ 5, 14, 29, 50],
       [ 2,  5, 14, 29],
       [ 5,  2,  5, 14]])

In [ ]:
n=len(A[0])
print(n)
ind=np.random.permutation(n)
A[:,ind]

3


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [ ]:
w,v=np.linalg.eig(A)
print(w)
sort_id = np.argsort(w)[-2:]
print(sort_id)
v[:, sort_id[::-1]]

[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]
[2 0]


array([[ 0.16476382,  0.40824829],
       [ 0.50577448, -0.81649658],
       [ 0.84678513,  0.40824829]])

In [ ]:
def linear_regression (X_tr, y_tr):
  A=np.dot(np.transpose(X_tr),X_tr)
  X=copy.deepcopy(X_tr)
  b=np.dot(X.transpose(),y_tr)
  w=np.linalg.solve(A,b)
  return w

def train_age_regressor ():
  # Load data
  print("load data")
  X_tr = np.reshape(np.load("/content/age_regression_Xtr.npy"), (-1, 48*48))
  new_col=np.ones((X_tr.shape[0],1))
  X_tr=np.hstack((X_tr, new_col))
  y_tr = np.load("/content/age_regression_ytr.npy")
  w= linear_regression(X_tr, y_tr)
  # print("done")
  return w.reshape(-1,1)

In [ ]:
w=train_age_regressor()
w


load data


array([[ 10.03075166],
       [ -4.66718623],
       [-18.03666814],
       ...,
       [-11.99892181],
       [  5.26799667],
       [ 37.61138638]])

In [ ]:
X_tr = np.reshape(np.load("/content/age_regression_Xtr.npy"), (-1, 48*48))
y_tr = np.load("/content/age_regression_ytr.npy")
X_te = np.reshape(np.load("/content/age_regression_Xte.npy"), (-1, 48*48))
y_te = np.load("/content/age_regression_yte.npy")
new_col=np.ones((X_tr.shape[0],1))
X_tr=np.hstack((X_tr, new_col))
new_col_2=np.ones((X_te.shape[0],1))
X_te=np.hstack((X_te, new_col_2))
fmse_tr=0
fmse_te=0
n=X_tr.shape[0]
m=X_te.shape[0]
for i in range(n):
  fmse_tr += (1/(2*n))*(np.dot(X_tr[i,:],w)- y_tr[i])*(np.dot(X_tr[i,:],w) - y_tr[i]) 
print(fmse_tr)
for i in range(m):
	fmse_te += (1/(2*m))*(np.dot(X_te[i,:],w)- y_te[i])*(np.dot(X_te[i,:],w)- y_te[i])
print(fmse_te) 

[39.24296299]
[206.79647485]
